### ISSUE TITLE
Inception Resnet v2 ValueError

### ISSUE THREAD

**Issue by JakubSerwatka** [isobar-us/multilabel-image-classification-tensorflow#3]
I've successfully trained the model, but when I'm trying to run label_image.py it throws
`ValueError: Cannot feed value of shape (1, 229, 229, 3) for Tensor 'import/Placeholder:0', which has shape '(?, 299, 299, 3)'`
the command im running is 
`python label_image.py --input_height=229 --input_width=229 --graph=/tmp/output_graph.pb --labels=labels.txt --input_layer=Placeholder --output_layer=final_result --image=test.jpg`

**Comment by JakubSerwatka** [comment]
I've tried resizing the vector to (299,299,3) but it threw a similar error

**Comment by rhossei2** [comment]
@JakubSerwatka have you tried passing 299 as height and width?
`python label_image.py --input_height=299--input_width=299--graph=/tmp/output_graph.pb --labels=labels.txt --input_layer=Placeholder --output_layer=final_result --image=test.jpg`

**Comment by JakubSerwatka** [comment]
Ok so your command works i dont understand how its possible since mine and yours commands are identical but thanks for help

**Comment by JakubSerwatka** [comment]
@rhossei2 I just realized what the mistake was, sorry for trouble, didn't notice 229 instead of 299 after long coding session
